---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lightspeed
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-observability-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-local-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
