---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  resourceProfile: balanced
  storageDeviceSets:
    - name: ocs-deviceset-localblock
      count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
          storageClassName: localblock
          volumeMode: Block
      placement: {}
      portable: false
      replica: 3
  monDataDirHostPath: /var/lib/rook
