---
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
  serviceMesh:
    managementState: Managed
    controlPlane:
      metricsCollection: Istio
      namespace: istio-system
  trustedCABundle:
    managementState: Managed
---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    dashboard:
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    aipipelines:
      managementState: Managed
    kserve:
      managementState: Managed
      nim:
        airGapped: false
        managementState: Managed
      rawDeploymentServiceConfig: Headless
    ray:
      managementState: Managed
    trustyai:
      managementState: Managed
      mcpGuardrailsMode: false
    kueue:
      managementState: Removed
      autoCreateQueues: false
      defaultClusterQueueName: default
      defaultLocalQueueName: default
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ogx:
      managementState: Managed
    aigateway:
      managementState: Managed
    trainingoperator:
      managementState: Removed
    trainer:
      managementState: Removed
    sparkoperator:
      managementState: Removed
    feastoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    llamastackoperator:
      managementState: Removed
