---
model_namespace: qwen3-4b
model_name: qwen3-4b
model_image: "quay.io/redhat-ai-services/modelcar-catalog:qwen3-4b"

# Resource limits for the model server
model_gpu_count: 1
model_cpu_limit: "4"
model_memory_limit: "16Gi"
model_cpu_request: "2"
model_memory_request: "8Gi"
model_max_model_len: 32768
model_max_output_tokens: 4096
